version: '3.8'

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_ACCOUNT_REGION}.amazonaws.com/midterm-backend:latest
    container_name: backend
    ports:
      - 3001:3001
    env_file:
      .env
    restart: always