version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data:/var/lib/mysql

  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG:-latest}
    ports:
      - 3001:3001
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom NGINX config file
      - ./frontend/build:/usr/share/nginx/html  # Mount the React build folder as the static file location
    ports:
      - "80:80"  # Expose port 80 to the host for external access
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app-network:
    driver: bridge