version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app-network
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX config file
      - ./frontend:/usr/share/nginx/html  # Mount the React build folder as the static file location
    ports:
      - "80:80"  # Expose port 80 to the host for external access
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge