name: Deploy to QA

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  # send-docker-compose:
  #   name: Send Docker Compose to QA Machine
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Infrastructure Repository
  #       uses: actions/checkout@v4
  #       with:
  #         path: infra

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: ${{ secrets.AWS_ACCOUNT_REGION }}
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

  #     - name: Set up SSH key
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa  # Ensure QA_SSH_PRIVATE_KEY is added to GitHub Secrets
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan -t rsa ${{ secrets.QA_EC2_HOST }} >> ~/.ssh/known_hosts  # Ensure QA_EC2_HOST is added to GitHub Secrets for your EC2 instance address.

  #     - name: Copy Docker Compose file to QA EC2 instance
  #       run: |
  #         # Adjust the path to where the docker-compose.yml is located.
  #         scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa infra/docker-compose.yml ec2-user@${{ secrets.QA_EC2_HOST }}:/path/to/target/directory
  #       env:
  #         QA_EC2_HOST: ${{ secrets.QA_EC2_HOST }}
######################################
      # - name: Leftovers
        
      #     docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/midterm-frontend:latest
      #     docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/midterm-backend:latest
      #     docker stop frontend-container || true
      #     docker rm frontend-container || true
      #     docker stop backend-container || true
      #     docker rm backend-container || true
      #     docker run -d --name frontend-container -p 3000:3000 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/midterm-frontend:latest
      #     docker run -d --name backend-container -p 3001:3001 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/midterm-backend:latest

  deploy-to-qa:
    name: Deploy build to QA
    runs-on: self-hosted

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_ACCOUNT_REGION }}
      
      - name: Run the setup script on machine
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCOUNT_REGION: ${{ secrets.AWS_ACCOUNT_REGION }}
        run: |
          /home/ec2-user/setup_QA_EC2.sh
      

