name: Deploy to QA

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy-to-qa:
    name: Deploy build to QA
    runs-on: self-hosted

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_ACCOUNT_REGION }}
      
      - name: Run the setup script on machine
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCOUNT_REGION: ${{ secrets.AWS_ACCOUNT_REGION }}
        run: |
          /home/ec2-user/setup_QA_EC2.sh
      

