name: Nightly Build, Test, and Deploy

on:
  schedule:
    - cron: "0 8 * * *"  # Runs every day at 12 AM Pacific time
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-test:
    name: Build and Test in EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: lawrenceslng/DevOps_Midterm_SPA
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Create Temp EC2 for Verification
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-05b10e08d247fb927 \
            --instance-type t2.micro \
            --security-group-ids sg-0a9e436f893e4e5e8 \
            --query 'Instances[0].InstanceId' --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          sleep 15 # Wait for EC2 to be ready
      
      ### Run some tests in EC2

      ### If success, push to ECR
      - name: push-to-ecr
        if: success()
        run: |
          echo "pushing to ecr"

      - name: deploy-to-qa-ec2
        if: success()
        run: |
          echo "deploying to qa"

      - name: Remove Temp EC2
        if: always()
        run: |
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID